apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-server
  template:
    metadata:
      labels:
        app: pokemon-server
    spec:
      containers:
        - name: pokemon-server
          image: nth786/pokemon-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-web
  template:
    metadata:
      labels:
        app: pokemon-web
    spec:
      containers:
        - name: pokemon-web
          image: nth786/pokemon-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-db
  template:
    metadata:
      labels:
        app: pokemon-db
    spec:
      containers:
        - name: pokemon-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
