apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokemon-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: pokemon.local
      http:
        paths:
          # Backend : /graphql
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: pokemon-server
                port:
                  number: 4000
          # Frontend : /
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pokemon-web
                port:
                  number: 80
